[1 of 3] issue #26: aws-as: add '-H' (--hoist) option
Two generated shell scripts are involved. The first, the "subshell
script", is supplied to an 'aws-vault' procress to be invoked by a
grandchild bash process. It plucks the 'AWS_*' credential variables out
of its environment and emits the second script (the "response script")
on stdout that sets the variables (basically a handful of 'declare -g
NAME=VALUE' statements).

The 'aws-as' command function running in the user's current shell eval's
the response script, thereby using the values obtained from the
subprocess to set the AWS_* credential variables in the current shell.

diff --git a/src/main/bash/bin/aws-as-activate.in b/src/main/bash/bin/aws-as-activate.in
--- a/src/main/bash/bin/aws-as-activate.in
+++ b/src/main/bash/bin/aws-as-activate.in
@@ -1,7 +1,9 @@
-#!/bin/bash -
+#!@BASH_SH@ -
 # SPDX-FileCopyrightText: <text> © 2020 Alan D. Salewski <salewski@att.net> </text>
 #
 # SPDX-License-Identifier: GPL-2.0-or-later
+
+# @configure_input@
 
 # aws-as-activate.in: Emits a handful of shell functions and metadata
 # variables that provide the 'aws-as' command (really a shell function) for
@@ -56,7 +58,9 @@ TRACING=false      # enable with three or more '-v' (--verbose) opts
 # (with hyphen chars changed to underscores).
 
 CAT_PROG="${CAT:-@CAT@}"
+SED_PROG="${SED:-@SED@}"
 
+BASH_PROG="${BASH:-@BASH_SH@}"
 #DATE_PROG="${DATE:-@DATE_PROG@}"
 TRUE_PROG="${TRUE:-@TRUE_PROG@}"
 
@@ -533,9 +537,12 @@ EOF
     t_cleanup_statements+=('${__t_v_aws_as_have_PS1_hold} && PS1=${__t_v_aws_as_PS1_hold}')
 
     t_cleanup_statements+=(':')
+    t_cleanup_statements+=('unset -v __T_V_AWS_AS_SED_PROG')
 #    t_cleanup_statements+=('unset -v __T_V_AWS_AS_AWS_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_AWS_VAULT_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_CHMOD_PROG')
+    t_cleanup_statements+=(':')
+    t_cleanup_statements+=('unset -v __T_V_AWS_AS_BASH_PROG')
 #    t_cleanup_statements+=('unset -v __T_V_AWS_AS_DATE_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_TRUE_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_MKDIR_PROG')
@@ -543,9 +550,12 @@ EOF
 
     "${CAT_PROG}" - <<EOF  # interpolating heredoc statements (okay)
 
+__T_V_AWS_AS_SED_PROG='${SED_PROG}'
 #__T_V_AWS_AS_AWS_PROG='${AWS_PROG}'
 __T_V_AWS_AS_AWS_VAULT_PROG='${AWS_VAULT_PROG}'
 __T_V_AWS_AS_CHMOD_PROG='${CHMOD_PROG}'
+
+__T_V_AWS_AS_BASH_PROG='${BASH_PROG}'
 #__T_V_AWS_AS_DATE_PROG='${DATE_PROG}'
 __T_V_AWS_AS_TRUE_PROG='${TRUE_PROG}'
 __T_V_AWS_AS_MKDIR_PROG='${MKDIR_PROG}'
@@ -656,6 +666,8 @@ EOF
     t_cleanup_statements+=(':')
     t_cleanup_statements+=('unset -f __t_f_aws_as_export_cred_vars')
     t_cleanup_statements+=('unset -f __t_f_aws_as_unexport_cred_vars')
+    t_cleanup_statements+=('unset -f __t_f_aws_as_maybe_hoist_cred_vars')
+    t_cleanup_statements+=(':')
     t_cleanup_statements+=('unset -f __t_f_aws_as_list_profiles')
     t_cleanup_statements+=('unset -f __t_f_aws_as_try_set_profile_as')
 
@@ -685,6 +697,7 @@ usage: \$__T_V_AWS_AS_PROG [-v...] { -h | --help }
   or:  \$__T_V_AWS_AS_PROG [-v...] { -c | --clear-env }
   or:  \$__T_V_AWS_AS_PROG [-v...] { -C | --clear-creds }
   or:  \$__T_V_AWS_AS_PROG [-v...] { -E | --export }
+  or:  \$__T_V_AWS_AS_PROG [-v...] { -H | --hoist }
   or:  \$__T_V_AWS_AS_PROG [-v...] { -L | --list-profiles }
   or:  \$__T_V_AWS_AS_PROG [-v...] { -U | --unexport }
   or:  \$__T_V_AWS_AS_PROG [OPTION...] [--] AWS_CLI_PROFILE
@@ -704,7 +717,13 @@ CAREFUL: Bundling of short-form options is not (yet?) supported.
                          Implies -c (--clear-creds) and --none.
 
   -E, --export         Mark the AWS_* credential variables for export
+                         Implies -H (--hoist).
+
   -U, --unexport       Un-mark the AWS_* creds vars for export (turn off 'x' attribute)
+                         Implies -H (--hoist).
+
+  -H, --hoist          "Hoist up" into the current environment AWS_* credential
+                         variables associated with the in-effect profile
 
   -L, --list-profiles  Print list of aws-cli profiles on stdout
 
@@ -871,6 +890,110 @@ function __t_f_aws_as_clear_cached_creds () {
 EOF
 
 
+    # Support for aws-as '-H' (--hoist) opt
+    # https://github.com/salewski/aws-as/issues/26
+    #
+    # If there is no in-effect profile, then __t_f_aws_as_maybe_hoist_cred_vars()
+    # is effectively a NOOP.
+    #
+    "${CAT_PROG}" - <<'EOF'
+
+function __t_f_aws_as_maybe_hoist_cred_vars () {
+
+    if test "${__T_V_AWS_AS_PROFILE}" = "${__T_V_AWS_AS_PROFILE_NONE}"; then
+        if ${__T_V_AWS_AS_BE_VERBOSE}; then
+            printf "${__T_V_AWS_AS_PROG} (info): no in-effect profile; nothing to tell aws-vault to hoist (okay)\n" 1>&2
+        fi
+        return 0
+    fi
+
+    local -a t_global_opts=()
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        t_global_opts+='--debug'
+    fi
+
+    local t_subshell_script
+    local t_response_script
+    local t_vname
+
+    t_subshell_script=': '$'\n'
+    if ${__T_V_AWS_AS_TRACING}; then
+        t_subshell_script="${t_subshell_script}"'set -x;'$'\n'
+    fi
+
+    # The resonse script will be evaled in the context of this function, so
+    # the generated 'declare -- FOO' statements are switch to 'declare -g FOO'
+    # so they will have the intended effect.
+    #
+    local t_check=''  # snippet 1
+    local t_noexp=''  # snippet 2
+    local t_declp=''  # snippet 3
+    local t_clean=''  # snippet 4
+
+    local t_combn=''  # above snippets, combined
+
+    for t_vname in 'AWS_PROFILE' 'AWS_ACCESS_KEY_ID' 'AWS_SECRET_ACCESS_KEY' 'AWS_SESSION_TOKEN'; do
+
+        t_check='test "${'"${t_vname}"'+is_set}" = "is_set" \'$'\n'
+
+        t_noexp='&& declare +x '"${t_vname}"' \'$'\n'
+
+        t_declp='&& declare -p '"${t_vname}"' \'$'\n'
+
+        # The resonse script will be eval'd in the context of this function, so the
+        # generated 'declare -- FOO' statements are switched to 'declare -g FOO'
+        # so they will have the intended effect of setting the global variable of
+        # the given name (rather than a local shell variable).
+        #
+        # We also ensure each line emitted ends with a semicolon.
+        #
+        t_clean='   | '"${__T_V_AWS_AS_SED_PROG}"' -e "s#^\(declare[[:space:]]\{1,\}\)--\([[:space:]]\{1,\}.*\)#\1-g\2#" -e "s#\$#\;#";'$'\n'
+
+        t_combn="${t_check}${t_noexp}${t_declp}${t_clean}"
+
+        t_subshell_script="${t_subshell_script}${t_combn}"
+    done
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug): generated subshell script for hoisting:\n---->8----\n%s\n----8<----\n" \
+            "${t_subshell_script}" 1>&2
+    fi
+
+    t_response_script=$("${__T_V_AWS_AS_AWS_VAULT_PROG}" "${t_global_opts[@]}" \
+                                                    exec "${__T_V_AWS_AS_PROFILE}" \
+                                                         -- "${__T_V_AWS_AS_BASH_PROG}" -c "${t_subshell_script}")
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): was error from aws-vault while generating env vars script for profile: %s\n" \
+            "${__T_V_AWS_AS_PROFILE}" 1>&2
+        return 1
+    fi
+
+    if test -z "${t_response_script}"; then
+        printf "${__T_V_AWS_AS_PROG} (error): generated env vars script is empty; unable to hoist 'AWS_*' credential vars settings into the current environment; stopping\n" 1>&2
+        return 1
+    fi
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug): generated response script for hoisting:\n---->8----\n%s\n----8<----\n" \
+            "${t_response_script}" 1>&2
+    fi
+
+    # The generated script constructed from the bash-generated output of
+    # 'declare -p' statements is safe to eval here.
+    #
+    eval "${t_response_script}"
+
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): hoisting failed: was error while evaluating the AWS_* cred. env var settings from subprocess\n" 1>&2
+        return 1
+    fi
+
+    return 0
+}
+EOF
+
+
     # Support for aws-as '-E' (--export) opt
     # https://github.com/salewski/aws-as/issues/3
     #
@@ -1002,7 +1125,7 @@ function __t_f_aws_as_try_set_profile_as () {
     fi
 
     if ${__T_V_AWS_AS_DEBUGGING}; then
-        printf "${__T_V_AWS_AS_PROG} (info): querying aws-cli for current list of profiles\n" 1>&2
+        printf "${__T_V_AWS_AS_PROG} (debug): querying aws-cli for current list of profiles\n" 1>&2
     fi
 
     local -a t_all_legit=()
@@ -1019,7 +1142,7 @@ function __t_f_aws_as_try_set_profile_as () {
     fi
 
     if ${__T_V_AWS_AS_DEBUGGING}; then
-        printf "${__T_V_AWS_AS_PROG} (info): aws-vault provided list of %d profiles\n" "${#t_all_legit[@]}" 1>&2
+        printf "${__T_V_AWS_AS_PROG} (debug): aws-vault provided list of %d profiles\n" "${#t_all_legit[@]}" 1>&2
     fi
 
     local t_is_legit=false
@@ -1132,6 +1255,12 @@ function __t_f_aws_as_main () {
                 __t_f_aws_as_unexport_cred_vars
                 return $?
                 ;;
+
+            '--hoist' | '-H')
+                __t_f_aws_as_maybe_hoist_cred_vars
+                return $?
+                ;;
+
 
             '--list-profiles' | '-L')
                 __t_f_aws_as_list_profiles
