[4 of 4] fixes #30: aws-as: '-c' (--clear-creds) now clears from aws-vault
The '-C' (--clear-creds) option can now be thought of as a stronger form
of '-c'. It implies the new '-c' (--clear-env) opt, but also requests
that 'aws-vault' clear the temporary credentials from its cache for the
in-effect aws-cli profile.

It also implies '--none', which unsets the in-effect profile (because
using the profile again may require re-authentication -- it no longer
has an active "session" with cached creds in the aws-vault cache).

diff --git a/src/main/bash/bin/aws-as-activate.in b/src/main/bash/bin/aws-as-activate.in
--- a/src/main/bash/bin/aws-as-activate.in
+++ b/src/main/bash/bin/aws-as-activate.in
@@ -651,6 +651,7 @@ EOF
     t_cleanup_statements+=('unset -f __t_f_aws_as_reset_dashv_flags')
     t_cleanup_statements+=(':')
     t_cleanup_statements+=('unset -f __t_f_aws_as_clear_env_of_creds')
+    t_cleanup_statements+=('unset -f __t_f_aws_as_clear_cached_creds')
     t_cleanup_statements+=('unset -f __t_f_aws_as_unset_ineffect_profile')
     t_cleanup_statements+=(':')
     t_cleanup_statements+=('unset -f __t_f_aws_as_export_cred_vars')
@@ -697,7 +698,10 @@ CAREFUL: Bundling of short-form options is not (yet?) supported.
   -V, --version        Print the version of the program on stdout
 
   -c, --clear-env      Unset AWS_* credential variables in the current environment
-  -C, --clear-creds    FIXME: WIP
+
+  -C, --clear-creds    Clear cached temporary credentials from the aws-vault cache
+                         for the in-effect aws-cli profile.
+                         Implies -c (--clear-creds) and --none.
 
   -E, --export         Mark the AWS_* credential variables for export
   -U, --unexport       Un-mark the AWS_* creds vars for export (turn off 'x' attribute)
@@ -762,8 +766,6 @@ function __t_f_aws_as_list_profiles () {
 EOF
 
 
-    # switch back to using non-interpolated heredoc
-    #
     "${CAT_PROG}" - <<'EOF'
 
 function __t_f_aws_as_clear_env_of_creds () {
@@ -801,6 +803,69 @@ function __t_f_aws_as_unset_ineffect_profile () {
 
     __T_V_AWS_AS_PROFILE=${__T_V_AWS_AS_PROFILE_NONE}
     __t_f_aws_as_maybe_update_PS1
+    return 0
+}
+EOF
+
+
+    # Ensures both of the following:
+    #
+    #     1. AWS_* cred. vars are cleared from the current shell environment.
+    #
+    #     2. That aws-vault clears the temporary creds for the in-effect
+    #        profile from its cache. If there is no in-effect profile, then
+    #        only (1) is done.
+    #
+    # Since clearing the cached creds in aws-vault means the in-effect profile
+    # will no longer be authenticated, this function implies an unsetting of
+    # the in-effect profile, as well.
+    #
+    "${CAT_PROG}" - <<'EOF'
+
+function __t_f_aws_as_clear_cached_creds () {
+
+    __t_f_aws_as_clear_env_of_creds
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): was error while clearing AWS_* cred. vars from current env; stopping\n" 1>&2
+        return 1
+    fi
+
+    if test "${__T_V_AWS_AS_PROFILE}" = "${__T_V_AWS_AS_PROFILE_NONE}"; then
+        if ${__T_V_AWS_AS_BE_VERBOSE}; then
+            printf "${__T_V_AWS_AS_PROG} (info): no in-effect profile; nothing to tell aws-vault to clear (okay)\n" 1>&2
+        fi
+        return 0
+    fi
+
+    if ${__T_V_AWS_AS_BE_VERBOSE}; then
+        printf "${__T_V_AWS_AS_PROG} (info): requesting that aws-vault clear cached creds for profile: %s\n" \
+            "${__T_V_AWS_AS_PROFILE}" 1>&2
+    fi
+
+    local -a t_global_opts=()
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        t_global_opts+='--debug'
+    fi
+
+    "${__T_V_AWS_AS_AWS_VAULT_PROG}" "${t_global_opts[@]}" clear "${__T_V_AWS_AS_PROFILE}"
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): was error from aws-vault while clearing cached creds for profile: %s\n" \
+            "${__T_V_AWS_AS_PROFILE}" 1>&2
+        return 1
+    fi
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug): triggering unset of the in-effect profile\n" 1>&2
+    fi
+
+    __t_f_aws_as_unset_ineffect_profile
+
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): was error while unsetting the in-effect profile\n" 1>&2
+        return 1
+    fi
+
     return 0
 }
 EOF
@@ -1046,10 +1111,17 @@ function __t_f_aws_as_main () {
                 return 0
                 ;;
 
+
             '--clear-env' | '-c')
                 __t_f_aws_as_clear_env_of_creds
                 return $?
                 ;;
+
+            '--clear-creds' | '-C')
+                __t_f_aws_as_clear_cached_creds
+                return $?
+                ;;
+
 
             '--export' | '-E')
                 __t_f_aws_as_export_cred_vars
