fixes #19: aws-as: obtain parsed creds through the cache, always
When fresh user (sts:GetSessionToken) or role (sts:AssumeRole) creds are
obtained from the AWS API (via aws-cli), the code used to parse the
creds out of the in-memory JSON response and use them directly, and
later write the response JSON to the cache file. That meant the
mechanism used to establish "fresh" creds was different from how the
creds would be read from the cache later on. That approach left room (in
the presence of bugs) for the thing in effect upon first use being
different from the thing that will be used in the future from the cache.

This change causes the response JSON to get written to the cache file
first, and the parsed credential values are then read back in through
the cache. The only credentials used are the ones read from our cache
interface. This will force problems in this area to the surface earlier,
and simplifies the implementation because we do the same thing in the
same way consistently with regard to obtaining credentials.

It also has the side effect of detecting (major) clock skew on the
machine earlier, which will force it to be dealt with. The previous
approach could leave the cache simply not working in such a scenario; in
some circumstance there would simply never be a cache hit for
non-expired credentials (if they always looked expired). With the new
approach, the "expired?" check is performed when the creds are read from
the cache; if the just-written fresh credentials are detected to be
expired, the program exits with an error hinting that the system clock
may need adjustment.

diff --git a/src/main/bash/bin/aws-as-activate.in b/src/main/bash/bin/aws-as-activate.in
--- a/src/main/bash/bin/aws-as-activate.in
+++ b/src/main/bash/bin/aws-as-activate.in
@@ -57,6 +57,7 @@ TRACING=false      # enable with three or more '-v' (--verbose) opts
 
 CAT_PROG="${CAT:-@CAT@}"
 CHMOD_PROG="${CHMOD:-@CHMOD_PROG@}"
+DATE_PROG="${DATE:-@DATE_PROG@}"
 MKDIR_PROG="${MKDIR:-@MKDIR_PROG@}"
 XARGS_PROG="${XARGS:-@XARGS_PROG@}"
 
@@ -532,6 +533,7 @@ EOF
     t_cleanup_statements+=(':')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_AWS_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_CHMOD_PROG')
+    t_cleanup_statements+=('unset -v __T_V_AWS_AS_DATE_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_MKDIR_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_PYTHON3_PROG')
     t_cleanup_statements+=('unset -v __T_V_AWS_AS_JQ_PROG')
@@ -541,6 +543,7 @@ EOF
 
 __T_V_AWS_AS_AWS_PROG='${AWS_PROG}'
 __T_V_AWS_AS_CHMOD_PROG='${CHMOD_PROG}'
+__T_V_AWS_AS_DATE_PROG='${DATE_PROG}'
 __T_V_AWS_AS_MKDIR_PROG='${MKDIR_PROG}'
 __T_V_AWS_AS_PYTHON3_PROG='${PYTHON3_PROG}'
 __T_V_AWS_AS_JQ_PROG='${JQ_PROG}'
@@ -1222,8 +1225,49 @@ else:
         # avoid leaving the creds around in the global variables
         #
         __t_v_aws_as_parsed_creds_reset || return 1
+    fi
 
+    # PORTABILITY: lowest-common denominator date(1) invocation intended to be
+    #              portable between GNU coreutils, FreeBSD, others. Emits UTC
+    #              date in ISO-8601 format, precise to the second.
+    local t_local_now_utc
+    t_local_now_utc=$("${__T_V_AWS_AS_DATE_PROG}" -u -Iseconds)
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): was unable to obtain current UTC timestamp in ISO-8601 format\n" 1>&2
+        return 1
+    fi
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug):          current timestamp: %s\n" "${t_local_now_utc}" 1>&2
+        printf "${__T_V_AWS_AS_PROG} (debug): creds expiration timestamp: %s\n" "${t_expiration_utc}" 1>&2
+    fi
+    # Test date strings using (ASCII) lexicographical ordering
+    #
+    if test "${t_local_now_utc}" \< "${t_expiration_utc}"; then
+        t_have_unexpired_creds=true
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): user creds have not yet expired\n" 1>&2
+        fi
+
+        # The credentials have not expired (because we are still
+        # within the time range of the originally requested duration
+        # seconds (or because the clock on the user's computer is
+        # wrong)). But having unexpired creds is no guarantee that
+        # the creds will actually work -- they may have been revoked,
+        # e.g., by administrative action; there's no way to really
+        # know without attempting to use them.
     else
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): cached user creds have expired\n" 1>&2
+        fi
+    fi
+
+    if $t_have_unexpired_creds; then :; else
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): will attempt to obtain fresh user creds\n" 1>&2
+        fi
 
         # obtain temporary creds (sts:GetSessionToken) and cache them in file
 
@@ -1307,38 +1351,23 @@ else:
             return 1
         fi
 
-        # read cached creds and expiration timestamp from raw JSON output
-        # (xargs is there to flatten multiple lines down into one)
-        read -r t_access_key_id     \
-                t_secret_access_key \
-                t_session_token     \
-                t_expiration_utc <  \
-            <("${__T_V_AWS_AS_XARGS_PROG}" < <("${__T_V_AWS_AS_JQ_PROG}" --raw-output \
-                '.Credentials | .AccessKeyId, .SecretAccessKey, .SessionToken, .Expiration' \
-                <<< "${t_raw_json_rsp}"))
-        if test $? -ne 0; then
-            printf "${__T_V_AWS_AS_PROG} (error): was unable to parse raw JSON output from get-session-token for profile: %s\n" \
-            "${t_profile_name}" 1>&2
-            return 1
-        fi
-        if test -z "${t_access_key_id}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty user access key from parsed session token creds\n" 1>&2
-            return 1
-        fi
-        if test -z "${t_secret_access_key}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty user secret access key from parsed session token creds\n" 1>&2
-            return 1
-        fi
-        if test -z "${t_session_token}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty user session token from parsed session token creds\n" 1>&2
-            return 1
-        fi
-        if test -z "${t_expiration_utc}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty user expiration timestamp from parsed session token creds\n" 1>&2
-            return 1
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): obtained fresh user creds\n" 1>&2
         fi
 
-        # create a new cache file for these temporary User creds
+        # Rather than use the credentials directly, we will write them to the
+        # cache file and then attempt to use the parsed content read back from
+        # the cache. This keeps the cached creds as our single source of truth,
+        # and helps surface earlier any problems with our cache implementation.
+        #
+        # See also:
+        #     https://github.com/salewski/aws-as/issues/19
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): writing fresh user creds to cache file: %s\n" "${t_fpath}" 1>&2
+        fi
+
+        # create a new (empty) cache file for these temporary User creds
         #
         > "${t_fpath}"
         if test $? -ne 0; then
@@ -1355,10 +1384,72 @@ else:
             printf "${__T_V_AWS_AS_PROG} (error): was unable to write JSON content to newly created user creds cache file: %s\n" "${t_fpath}" 1>&2
             return 1
         fi
+
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): attempting to read back in the fresh user creds just written to the cache file: %s\n" "${t_fpath}" 1>&2
+        fi
+        __t_v_aws_as_parsed_creds_reset || return 1
+        __t_f_aws_as_parse_creds_from_cache_file "${t_fpath}" 'user' \
+            '__T_V_AWS_AS_PARSED_CRED_ACCESS_KEY_ID'     \
+            '__T_V_AWS_AS_PARSED_CRED_SECRET_ACCESS_KEY' \
+            '__T_V_AWS_AS_PARSED_CRED_SESSION_TOKEN'     \
+            '__T_V_AWS_AS_PARSED_CRED_EXPIRATION_UTC'
+        if test $? -ne 0; then
+            printf "${__T_V_AWS_AS_PROG} (error): was unable to read newly obtained user creds back from the cache\n" \
+                "${t_fpath}" 1>&2
+            return 1
+        fi
+        t_access_key_id=${__T_V_AWS_AS_PARSED_CRED_ACCESS_KEY_ID}
+        t_secret_access_key=${__T_V_AWS_AS_PARSED_CRED_SECRET_ACCESS_KEY}
+        t_session_token=${__T_V_AWS_AS_PARSED_CRED_SESSION_TOKEN}
+        t_expiration_utc=${__T_V_AWS_AS_PARSED_CRED_EXPIRATION_UTC}
+
+        # avoid leaving the creds around in the global variables
+        #
+        __t_v_aws_as_parsed_creds_reset || return 1
+
+
+        # Ensure that the creds we just read back in do not look expired to
+        # us. This should succeed unless the clock on the machine is too far
+        # off. Note that we are comparing the cached expiration timestamp
+        # (which was received from AWS) with a "now" timestamp generated on
+        # the local machine.
+        #
+        # See also above earlier notes about the portability of our date(1)
+        # invocation for this purpose.
+        #
+        # Obtain a new "now" timestamp. If user needed to provide an MFA token
+        # to authenticate above, the difference between the current time and our
+        # earlier obtained "now" value could be significant.
+        #
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): verifying expiration of the fresh user creds from the cache file: %s\n" "${t_fpath}" 1>&2
+        fi
+        t_local_now_utc=$("${__T_V_AWS_AS_DATE_PROG}" -u -Iseconds)
+        if test $? -ne 0; then
+            printf "${__T_V_AWS_AS_PROG} (error): was unable to obtain current UTC timestamp in ISO-8601 format\n" 1>&2
+            return 1
+        fi
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug):                current timestamp: %s\n" "${t_local_now_utc}" 1>&2
+            printf "${__T_V_AWS_AS_PROG} (debug): (new) creds expiration timestamp: %s\n" "${t_expiration_utc}" 1>&2
+        fi
+        # Test date strings using (ASCII) lexicographical ordering
+        #
+        if test "${t_local_now_utc}" \< "${t_expiration_utc}"; then :; else
+            printf "${__T_V_AWS_AS_PROG} (error): \"just cached\" user creds look expired; system clock misconfigured? (creds cache file: %s)\n" \
+                "${t_fpath}" 1>&2
+            return 1
+        fi
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): newly obtained user creds look good\n" 1>&2
+        fi
     fi
 
-    # place user creds into environment
-    #
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug): placing user creds into the environment\n" 1>&2
+    fi
     AWS_ACCESS_KEY_ID=${t_access_key_id}
     AWS_SECRET_ACCESS_KEY=${t_secret_access_key}
     AWS_SESSION_TOKEN=${t_session_token}
@@ -1391,7 +1482,7 @@ function __t_f_aws_as_try_set_profile_as_for_role () {
     local t_role_sessn=$("${__T_V_AWS_AS_AWS_PROG}" --profile "${t_profile_name}" configure get 'role_session_name')
 
     # Any needed MFA-based authorization activity should have been taken
-    # care of by the time the current function is called, but we stil lookup
+    # care of by the time the current function is called, but we still lookup
     # the MFA device serial number here for use in our cache file keys. This
     # keeps our cachefile key generation close/identical to the scheme used
     # by aws-cli.
@@ -1506,6 +1597,8 @@ else:
         fi
     fi
 
+    local t_have_unexpired_creds=false
+
     local t_access_key_id
     local t_secret_access_key
     local t_session_token
@@ -1534,8 +1627,49 @@ else:
         # avoid leaving the creds around in the global variables
         #
         __t_v_aws_as_parsed_creds_reset || return 1
+    fi
 
+    # PORTABILITY: lowest-common denominator date(1) invocation intended to be
+    #              portable between GNU coreutils, FreeBSD, others. Emits UTC
+    #              date in ISO-8601 format, precise to the second.
+    local t_local_now_utc
+    t_local_now_utc=$("${__T_V_AWS_AS_DATE_PROG}" -u -Iseconds)
+    if test $? -ne 0; then
+        printf "${__T_V_AWS_AS_PROG} (error): was unable to obtain current UTC timestamp in ISO-8601 format\n" 1>&2
+        return 1
+    fi
+
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug):          current timestamp: %s\n" "${t_local_now_utc}" 1>&2
+        printf "${__T_V_AWS_AS_PROG} (debug): creds expiration timestamp: %s\n" "${t_expiration_utc}" 1>&2
+    fi
+    # Test date strings using (ASCII) lexicographical ordering
+    #
+    if test "${t_local_now_utc}" \< "${t_expiration_utc}"; then
+        t_have_unexpired_creds=true
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): role creds have not yet expired\n" 1>&2
+        fi
+
+        # The credentials have not expired (because we are still
+        # within the time range of the originally requested duration
+        # seconds (or because the clock on the user's computer is
+        # wrong)). But having unexpired creds is no guarantee that
+        # the creds will actually work -- they may have been revoked,
+        # e.g., by administrative action; there's no way to really
+        # know without attempting to use them.
     else
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): cached role creds have expired\n" 1>&2
+        fi
+    fi
+
+    if $t_have_unexpired_creds; then :; else
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): will attempt to obtain fresh role creds\n" 1>&2
+        fi
 
         # obtain temporary creds (sts:AssumeRole) and cache them in file
 
@@ -1596,38 +1730,23 @@ else:
             return 1
         fi
 
-        # read cached creds and expiration timestamp from raw JSON output
-        # (xargs is there to flatten multiple lines down into one)
-        read -r t_access_key_id     \
-                t_secret_access_key \
-                t_session_token     \
-                t_expiration_utc <  \
-            <("${__T_V_AWS_AS_XARGS_PROG}" < <("${__T_V_AWS_AS_JQ_PROG}" --raw-output \
-                '.Credentials | .AccessKeyId, .SecretAccessKey, .SessionToken, .Expiration' \
-                <<< "${t_raw_json_rsp}"))
-        if test $? -ne 0; then
-            printf "${__T_V_AWS_AS_PROG} (error): was unable to parse raw JSON output from assume-role for role %s (from profile: %s)\n" \
-            "${t_role_arn}" "${t_profile_name}" 1>&2
-            return 1
-        fi
-        if test -z "${t_access_key_id}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty role access key from parsed session token creds\n" 1>&2
-            return 1
-        fi
-        if test -z "${t_secret_access_key}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty role secret access key from parsed session token creds\n" 1>&2
-            return 1
-        fi
-        if test -z "${t_session_token}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty role session token from parsed session token creds\n" 1>&2
-            return 1
-        fi
-        if test -z "${t_expiration_utc}"; then
-            printf "${__T_V_AWS_AS_PROG} (error): obtained empty role expiration timestamp from parsed session token creds\n" 1>&2
-            return 1
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): obtained fresh role creds\n" 1>&2
         fi
 
-        # create a new cache file for these temporary User creds
+        # Rather than use the credentials directly, we will write them to the
+        # cache file and then attempt to use the parsed content read back from
+        # the cache. This keeps the cached creds as our single source of truth,
+        # and helps surface earlier any problems with our cache implementation.
+        #
+        # See also:
+        #     https://github.com/salewski/aws-as/issues/19
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): writing fresh role creds to cache file: %s\n" "${t_fpath}" 1>&2
+        fi
+
+        # create a new (empty) cache file for these temporary Role creds
         #
         > "${t_fpath}"
         if test $? -ne 0; then
@@ -1644,10 +1763,65 @@ else:
             printf "${__T_V_AWS_AS_PROG} (error): was unable to write JSON content to newly created role creds cache file: %s\n" "${t_fpath}" 1>&2
             return 1
         fi
+
+
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): attempting to read back in the fresh role creds just written to the cache file: %s\n" "${t_fpath}" 1>&2
+        fi
+        __t_v_aws_as_parsed_creds_reset || return 1
+        __t_f_aws_as_parse_creds_from_cache_file "${t_fpath}" 'role' \
+            '__T_V_AWS_AS_PARSED_CRED_ACCESS_KEY_ID'     \
+            '__T_V_AWS_AS_PARSED_CRED_SECRET_ACCESS_KEY' \
+            '__T_V_AWS_AS_PARSED_CRED_SESSION_TOKEN'     \
+            '__T_V_AWS_AS_PARSED_CRED_EXPIRATION_UTC'
+        if test $? -ne 0; then
+            printf "${__T_V_AWS_AS_PROG} (error): was unable to read newly obtained role creds back from the cache\n" \
+                "${t_fpath}" 1>&2
+            return 1
+        fi
+        t_access_key_id=${__T_V_AWS_AS_PARSED_CRED_ACCESS_KEY_ID}
+        t_secret_access_key=${__T_V_AWS_AS_PARSED_CRED_SECRET_ACCESS_KEY}
+        t_session_token=${__T_V_AWS_AS_PARSED_CRED_SESSION_TOKEN}
+        t_expiration_utc=${__T_V_AWS_AS_PARSED_CRED_EXPIRATION_UTC}
+
+        # avoid leaving the creds around in the global variables
+        #
+        __t_v_aws_as_parsed_creds_reset || return 1
+
+
+        # Ensure that the creds we just read back in do not look expired to
+        # us. This should succeed unless the clock on the machine is too far
+        # off. Note that we are comparing the cached expiration timestamp
+        # (which was received from AWS) with a "now" timestamp generated on
+        # the local machine.
+        #
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): verifying expiration of the fresh role creds from the cache file: %s\n" "${t_fpath}" 1>&2
+        fi
+        t_local_now_utc=$("${__T_V_AWS_AS_DATE_PROG}" -u -Iseconds)
+        if test $? -ne 0; then
+            printf "${__T_V_AWS_AS_PROG} (error): was unable to obtain current UTC timestamp in ISO-8601 format\n" 1>&2
+            return 1
+        fi
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug):                current timestamp: %s\n" "${t_local_now_utc}" 1>&2
+            printf "${__T_V_AWS_AS_PROG} (debug): (new) creds expiration timestamp: %s\n" "${t_expiration_utc}" 1>&2
+        fi
+        # Test date strings using (ASCII) lexicographical ordering
+        #
+        if test "${t_local_now_utc}" \< "${t_expiration_utc}"; then :; else
+            printf "${__T_V_AWS_AS_PROG} (error): \"just cached\" role creds look expired; system clock misconfigured? (creds cache file: %s)\n" \
+                "${t_fpath}" 1>&2
+            return 1
+        fi
+        if ${__T_V_AWS_AS_DEBUGGING}; then
+            printf "${__T_V_AWS_AS_PROG} (debug): newly obtained role creds look good\n" 1>&2
+        fi
     fi
 
-    # place role creds into environment
-    #
+    if ${__T_V_AWS_AS_DEBUGGING}; then
+        printf "${__T_V_AWS_AS_PROG} (debug): placing role creds into the environment\n" 1>&2
+    fi
     AWS_ACCESS_KEY_ID=${t_access_key_id}
     AWS_SECRET_ACCESS_KEY=${t_secret_access_key}
     AWS_SESSION_TOKEN=${t_session_token}
